---
title: "Notebook: Laboratorio 2 de Econometría"
output: html_notebook
---

```{r}
## instalacion de librerias
## install.packages("corrplot")
## install.packages("matlib")

```


```{r}
## Import de librerias a utilizar

library(dplyr)
library(ggplot2)
library(matlib)
library(corrplot)
library(magrittr)

```



```{r}
## Carga de datos desde el .csv
dataset<-read.csv("Admission_Predict_Ver1.1.csv")
titulos<-c("serie","gre","toefl", "raiting","sop","lor","gcpa","reser","chance")

colnames(dataset) <- titulos

## Separacion de datos

y<- dataset$serie  ## Se obtiene el vector 
variables<- dataset[2:4]  ## conjunto de demas variables

##Prints
y
variables

```

```{r}
## len del dataset
tamanio<- nrow(dataset)

# matriz de Identidad en base al tamanio
identidad = data.matrix(rep(1,tamanio)) 
k <- cbind(identidad,variables)

## Se agrega columna de unos a las variables.
variables <-  as.matrix(k) 

# Resolviendo la ecuacion
parametros <- solve((t(variables)%*%variables)) %*% t(variables)%*%y 
parametros
```


```{r}
## encontrando perturbaciones
e= y - variables%*%parametros
```

```{r}
ii <- diag(1, nrow=tamanio)

# Utilizando la ecuacion 
Mo <-  ii - (1/tamanio) * identidad  %*% t(identidad)

# coeficiente
coeficienteR2 <- 1- (t(e) %*% e)/(t(y)%*%Mo%*%y)
coeficienteR2
```



Comparando contra el modelo utilizado por la función nativa de R
```{r}
lmR = lm(data=dataset,formula = dataset$serie~dataset$gre + dataset$toefl+dataset$raiting)
summary(lmR)

```





#######################################################################
### Conclusión:   Se logra definir el modelo por medio de matrices.
#######################################################################


